// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/disism/saikan/ent/albums"
	"github.com/disism/saikan/ent/artists"
	"github.com/disism/saikan/ent/images"
	"github.com/disism/saikan/ent/musics"
	"github.com/disism/saikan/ent/predicate"
	"github.com/disism/saikan/ent/users"
)

// AlbumsQuery is the builder for querying Albums entities.
type AlbumsQuery struct {
	config
	ctx         *QueryContext
	order       []albums.OrderOption
	inters      []Interceptor
	predicates  []predicate.Albums
	withImage   *ImagesQuery
	withMusics  *MusicsQuery
	withUsers   *UsersQuery
	withArtists *ArtistsQuery
	withFKs     bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AlbumsQuery builder.
func (aq *AlbumsQuery) Where(ps ...predicate.Albums) *AlbumsQuery {
	aq.predicates = append(aq.predicates, ps...)
	return aq
}

// Limit the number of records to be returned by this query.
func (aq *AlbumsQuery) Limit(limit int) *AlbumsQuery {
	aq.ctx.Limit = &limit
	return aq
}

// Offset to start from.
func (aq *AlbumsQuery) Offset(offset int) *AlbumsQuery {
	aq.ctx.Offset = &offset
	return aq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (aq *AlbumsQuery) Unique(unique bool) *AlbumsQuery {
	aq.ctx.Unique = &unique
	return aq
}

// Order specifies how the records should be ordered.
func (aq *AlbumsQuery) Order(o ...albums.OrderOption) *AlbumsQuery {
	aq.order = append(aq.order, o...)
	return aq
}

// QueryImage chains the current query on the "image" edge.
func (aq *AlbumsQuery) QueryImage() *ImagesQuery {
	query := (&ImagesClient{config: aq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(albums.Table, albums.FieldID, selector),
			sqlgraph.To(images.Table, images.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, albums.ImageTable, albums.ImageColumn),
		)
		fromU = sqlgraph.SetNeighbors(aq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMusics chains the current query on the "musics" edge.
func (aq *AlbumsQuery) QueryMusics() *MusicsQuery {
	query := (&MusicsClient{config: aq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(albums.Table, albums.FieldID, selector),
			sqlgraph.To(musics.Table, musics.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, albums.MusicsTable, albums.MusicsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(aq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUsers chains the current query on the "users" edge.
func (aq *AlbumsQuery) QueryUsers() *UsersQuery {
	query := (&UsersClient{config: aq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(albums.Table, albums.FieldID, selector),
			sqlgraph.To(users.Table, users.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, albums.UsersTable, albums.UsersPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(aq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryArtists chains the current query on the "artists" edge.
func (aq *AlbumsQuery) QueryArtists() *ArtistsQuery {
	query := (&ArtistsClient{config: aq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(albums.Table, albums.FieldID, selector),
			sqlgraph.To(artists.Table, artists.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, albums.ArtistsTable, albums.ArtistsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(aq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Albums entity from the query.
// Returns a *NotFoundError when no Albums was found.
func (aq *AlbumsQuery) First(ctx context.Context) (*Albums, error) {
	nodes, err := aq.Limit(1).All(setContextOp(ctx, aq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{albums.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (aq *AlbumsQuery) FirstX(ctx context.Context) *Albums {
	node, err := aq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Albums ID from the query.
// Returns a *NotFoundError when no Albums ID was found.
func (aq *AlbumsQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = aq.Limit(1).IDs(setContextOp(ctx, aq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{albums.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (aq *AlbumsQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := aq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Albums entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Albums entity is found.
// Returns a *NotFoundError when no Albums entities are found.
func (aq *AlbumsQuery) Only(ctx context.Context) (*Albums, error) {
	nodes, err := aq.Limit(2).All(setContextOp(ctx, aq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{albums.Label}
	default:
		return nil, &NotSingularError{albums.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (aq *AlbumsQuery) OnlyX(ctx context.Context) *Albums {
	node, err := aq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Albums ID in the query.
// Returns a *NotSingularError when more than one Albums ID is found.
// Returns a *NotFoundError when no entities are found.
func (aq *AlbumsQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = aq.Limit(2).IDs(setContextOp(ctx, aq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{albums.Label}
	default:
		err = &NotSingularError{albums.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (aq *AlbumsQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := aq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AlbumsSlice.
func (aq *AlbumsQuery) All(ctx context.Context) ([]*Albums, error) {
	ctx = setContextOp(ctx, aq.ctx, "All")
	if err := aq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Albums, *AlbumsQuery]()
	return withInterceptors[[]*Albums](ctx, aq, qr, aq.inters)
}

// AllX is like All, but panics if an error occurs.
func (aq *AlbumsQuery) AllX(ctx context.Context) []*Albums {
	nodes, err := aq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Albums IDs.
func (aq *AlbumsQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if aq.ctx.Unique == nil && aq.path != nil {
		aq.Unique(true)
	}
	ctx = setContextOp(ctx, aq.ctx, "IDs")
	if err = aq.Select(albums.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (aq *AlbumsQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := aq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (aq *AlbumsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, aq.ctx, "Count")
	if err := aq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, aq, querierCount[*AlbumsQuery](), aq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (aq *AlbumsQuery) CountX(ctx context.Context) int {
	count, err := aq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (aq *AlbumsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, aq.ctx, "Exist")
	switch _, err := aq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (aq *AlbumsQuery) ExistX(ctx context.Context) bool {
	exist, err := aq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AlbumsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (aq *AlbumsQuery) Clone() *AlbumsQuery {
	if aq == nil {
		return nil
	}
	return &AlbumsQuery{
		config:      aq.config,
		ctx:         aq.ctx.Clone(),
		order:       append([]albums.OrderOption{}, aq.order...),
		inters:      append([]Interceptor{}, aq.inters...),
		predicates:  append([]predicate.Albums{}, aq.predicates...),
		withImage:   aq.withImage.Clone(),
		withMusics:  aq.withMusics.Clone(),
		withUsers:   aq.withUsers.Clone(),
		withArtists: aq.withArtists.Clone(),
		// clone intermediate query.
		sql:  aq.sql.Clone(),
		path: aq.path,
	}
}

// WithImage tells the query-builder to eager-load the nodes that are connected to
// the "image" edge. The optional arguments are used to configure the query builder of the edge.
func (aq *AlbumsQuery) WithImage(opts ...func(*ImagesQuery)) *AlbumsQuery {
	query := (&ImagesClient{config: aq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	aq.withImage = query
	return aq
}

// WithMusics tells the query-builder to eager-load the nodes that are connected to
// the "musics" edge. The optional arguments are used to configure the query builder of the edge.
func (aq *AlbumsQuery) WithMusics(opts ...func(*MusicsQuery)) *AlbumsQuery {
	query := (&MusicsClient{config: aq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	aq.withMusics = query
	return aq
}

// WithUsers tells the query-builder to eager-load the nodes that are connected to
// the "users" edge. The optional arguments are used to configure the query builder of the edge.
func (aq *AlbumsQuery) WithUsers(opts ...func(*UsersQuery)) *AlbumsQuery {
	query := (&UsersClient{config: aq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	aq.withUsers = query
	return aq
}

// WithArtists tells the query-builder to eager-load the nodes that are connected to
// the "artists" edge. The optional arguments are used to configure the query builder of the edge.
func (aq *AlbumsQuery) WithArtists(opts ...func(*ArtistsQuery)) *AlbumsQuery {
	query := (&ArtistsClient{config: aq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	aq.withArtists = query
	return aq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Albums.Query().
//		GroupBy(albums.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (aq *AlbumsQuery) GroupBy(field string, fields ...string) *AlbumsGroupBy {
	aq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AlbumsGroupBy{build: aq}
	grbuild.flds = &aq.ctx.Fields
	grbuild.label = albums.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.Albums.Query().
//		Select(albums.FieldCreateTime).
//		Scan(ctx, &v)
func (aq *AlbumsQuery) Select(fields ...string) *AlbumsSelect {
	aq.ctx.Fields = append(aq.ctx.Fields, fields...)
	sbuild := &AlbumsSelect{AlbumsQuery: aq}
	sbuild.label = albums.Label
	sbuild.flds, sbuild.scan = &aq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AlbumsSelect configured with the given aggregations.
func (aq *AlbumsQuery) Aggregate(fns ...AggregateFunc) *AlbumsSelect {
	return aq.Select().Aggregate(fns...)
}

func (aq *AlbumsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range aq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, aq); err != nil {
				return err
			}
		}
	}
	for _, f := range aq.ctx.Fields {
		if !albums.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if aq.path != nil {
		prev, err := aq.path(ctx)
		if err != nil {
			return err
		}
		aq.sql = prev
	}
	return nil
}

func (aq *AlbumsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Albums, error) {
	var (
		nodes       = []*Albums{}
		withFKs     = aq.withFKs
		_spec       = aq.querySpec()
		loadedTypes = [4]bool{
			aq.withImage != nil,
			aq.withMusics != nil,
			aq.withUsers != nil,
			aq.withArtists != nil,
		}
	)
	if aq.withImage != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, albums.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Albums).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Albums{config: aq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, aq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := aq.withImage; query != nil {
		if err := aq.loadImage(ctx, query, nodes, nil,
			func(n *Albums, e *Images) { n.Edges.Image = e }); err != nil {
			return nil, err
		}
	}
	if query := aq.withMusics; query != nil {
		if err := aq.loadMusics(ctx, query, nodes,
			func(n *Albums) { n.Edges.Musics = []*Musics{} },
			func(n *Albums, e *Musics) { n.Edges.Musics = append(n.Edges.Musics, e) }); err != nil {
			return nil, err
		}
	}
	if query := aq.withUsers; query != nil {
		if err := aq.loadUsers(ctx, query, nodes,
			func(n *Albums) { n.Edges.Users = []*Users{} },
			func(n *Albums, e *Users) { n.Edges.Users = append(n.Edges.Users, e) }); err != nil {
			return nil, err
		}
	}
	if query := aq.withArtists; query != nil {
		if err := aq.loadArtists(ctx, query, nodes,
			func(n *Albums) { n.Edges.Artists = []*Artists{} },
			func(n *Albums, e *Artists) { n.Edges.Artists = append(n.Edges.Artists, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (aq *AlbumsQuery) loadImage(ctx context.Context, query *ImagesQuery, nodes []*Albums, init func(*Albums), assign func(*Albums, *Images)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*Albums)
	for i := range nodes {
		if nodes[i].images_albums == nil {
			continue
		}
		fk := *nodes[i].images_albums
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(images.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "images_albums" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (aq *AlbumsQuery) loadMusics(ctx context.Context, query *MusicsQuery, nodes []*Albums, init func(*Albums), assign func(*Albums, *Musics)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uint64]*Albums)
	nids := make(map[uint64]map[*Albums]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(albums.MusicsTable)
		s.Join(joinT).On(s.C(musics.FieldID), joinT.C(albums.MusicsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(albums.MusicsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(albums.MusicsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := uint64(values[0].(*sql.NullInt64).Int64)
				inValue := uint64(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Albums]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Musics](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "musics" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (aq *AlbumsQuery) loadUsers(ctx context.Context, query *UsersQuery, nodes []*Albums, init func(*Albums), assign func(*Albums, *Users)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uint64]*Albums)
	nids := make(map[uint64]map[*Albums]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(albums.UsersTable)
		s.Join(joinT).On(s.C(users.FieldID), joinT.C(albums.UsersPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(albums.UsersPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(albums.UsersPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := uint64(values[0].(*sql.NullInt64).Int64)
				inValue := uint64(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Albums]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Users](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "users" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (aq *AlbumsQuery) loadArtists(ctx context.Context, query *ArtistsQuery, nodes []*Albums, init func(*Albums), assign func(*Albums, *Artists)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uint64]*Albums)
	nids := make(map[uint64]map[*Albums]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(albums.ArtistsTable)
		s.Join(joinT).On(s.C(artists.FieldID), joinT.C(albums.ArtistsPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(albums.ArtistsPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(albums.ArtistsPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := uint64(values[0].(*sql.NullInt64).Int64)
				inValue := uint64(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Albums]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Artists](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "artists" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (aq *AlbumsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := aq.querySpec()
	_spec.Node.Columns = aq.ctx.Fields
	if len(aq.ctx.Fields) > 0 {
		_spec.Unique = aq.ctx.Unique != nil && *aq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, aq.driver, _spec)
}

func (aq *AlbumsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(albums.Table, albums.Columns, sqlgraph.NewFieldSpec(albums.FieldID, field.TypeUint64))
	_spec.From = aq.sql
	if unique := aq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if aq.path != nil {
		_spec.Unique = true
	}
	if fields := aq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, albums.FieldID)
		for i := range fields {
			if fields[i] != albums.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := aq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := aq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := aq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := aq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (aq *AlbumsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(aq.driver.Dialect())
	t1 := builder.Table(albums.Table)
	columns := aq.ctx.Fields
	if len(columns) == 0 {
		columns = albums.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if aq.sql != nil {
		selector = aq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if aq.ctx.Unique != nil && *aq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range aq.predicates {
		p(selector)
	}
	for _, p := range aq.order {
		p(selector)
	}
	if offset := aq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := aq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AlbumsGroupBy is the group-by builder for Albums entities.
type AlbumsGroupBy struct {
	selector
	build *AlbumsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (agb *AlbumsGroupBy) Aggregate(fns ...AggregateFunc) *AlbumsGroupBy {
	agb.fns = append(agb.fns, fns...)
	return agb
}

// Scan applies the selector query and scans the result into the given value.
func (agb *AlbumsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, agb.build.ctx, "GroupBy")
	if err := agb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AlbumsQuery, *AlbumsGroupBy](ctx, agb.build, agb, agb.build.inters, v)
}

func (agb *AlbumsGroupBy) sqlScan(ctx context.Context, root *AlbumsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(agb.fns))
	for _, fn := range agb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*agb.flds)+len(agb.fns))
		for _, f := range *agb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*agb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := agb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AlbumsSelect is the builder for selecting fields of Albums entities.
type AlbumsSelect struct {
	*AlbumsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (as *AlbumsSelect) Aggregate(fns ...AggregateFunc) *AlbumsSelect {
	as.fns = append(as.fns, fns...)
	return as
}

// Scan applies the selector query and scans the result into the given value.
func (as *AlbumsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, as.ctx, "Select")
	if err := as.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AlbumsQuery, *AlbumsSelect](ctx, as.AlbumsQuery, as, as.inters, v)
}

func (as *AlbumsSelect) sqlScan(ctx context.Context, root *AlbumsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(as.fns))
	for _, fn := range as.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*as.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := as.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
