// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/disism/saikan/ent/audiobooks"
	"github.com/disism/saikan/ent/predicate"
)

// AudiobooksUpdate is the builder for updating Audiobooks entities.
type AudiobooksUpdate struct {
	config
	hooks    []Hook
	mutation *AudiobooksMutation
}

// Where appends a list predicates to the AudiobooksUpdate builder.
func (au *AudiobooksUpdate) Where(ps ...predicate.Audiobooks) *AudiobooksUpdate {
	au.mutation.Where(ps...)
	return au
}

// Mutation returns the AudiobooksMutation object of the builder.
func (au *AudiobooksUpdate) Mutation() *AudiobooksMutation {
	return au.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AudiobooksUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AudiobooksUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AudiobooksUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AudiobooksUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

func (au *AudiobooksUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(audiobooks.Table, audiobooks.Columns, sqlgraph.NewFieldSpec(audiobooks.FieldID, field.TypeInt))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{audiobooks.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AudiobooksUpdateOne is the builder for updating a single Audiobooks entity.
type AudiobooksUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AudiobooksMutation
}

// Mutation returns the AudiobooksMutation object of the builder.
func (auo *AudiobooksUpdateOne) Mutation() *AudiobooksMutation {
	return auo.mutation
}

// Where appends a list predicates to the AudiobooksUpdate builder.
func (auo *AudiobooksUpdateOne) Where(ps ...predicate.Audiobooks) *AudiobooksUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AudiobooksUpdateOne) Select(field string, fields ...string) *AudiobooksUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Audiobooks entity.
func (auo *AudiobooksUpdateOne) Save(ctx context.Context) (*Audiobooks, error) {
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AudiobooksUpdateOne) SaveX(ctx context.Context) *Audiobooks {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AudiobooksUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AudiobooksUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (auo *AudiobooksUpdateOne) sqlSave(ctx context.Context) (_node *Audiobooks, err error) {
	_spec := sqlgraph.NewUpdateSpec(audiobooks.Table, audiobooks.Columns, sqlgraph.NewFieldSpec(audiobooks.FieldID, field.TypeInt))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Audiobooks.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, audiobooks.FieldID)
		for _, f := range fields {
			if !audiobooks.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != audiobooks.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &Audiobooks{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{audiobooks.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
