// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/disism/saikan/ent/dir"
	"github.com/disism/saikan/ent/user"
)

// Dir is the model entity for the Dir schema.
type Dir struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DirQuery when eager-loading is set.
	Edges        DirEdges `json:"edges"`
	user_dirs    *uint64
	selectValues sql.SelectValues
}

// DirEdges holds the relations/edges for other nodes in the graph.
type DirEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// Saves holds the value of the saves edge.
	Saves []*Saved `json:"saves,omitempty"`
	// Subdir holds the value of the subdir edge.
	Subdir []*Dir `json:"subdir,omitempty"`
	// Pdir holds the value of the pdir edge.
	Pdir []*Dir `json:"pdir,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DirEdges) OwnerOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.Owner == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.Owner, nil
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// SavesOrErr returns the Saves value or an error if the edge
// was not loaded in eager-loading.
func (e DirEdges) SavesOrErr() ([]*Saved, error) {
	if e.loadedTypes[1] {
		return e.Saves, nil
	}
	return nil, &NotLoadedError{edge: "saves"}
}

// SubdirOrErr returns the Subdir value or an error if the edge
// was not loaded in eager-loading.
func (e DirEdges) SubdirOrErr() ([]*Dir, error) {
	if e.loadedTypes[2] {
		return e.Subdir, nil
	}
	return nil, &NotLoadedError{edge: "subdir"}
}

// PdirOrErr returns the Pdir value or an error if the edge
// was not loaded in eager-loading.
func (e DirEdges) PdirOrErr() ([]*Dir, error) {
	if e.loadedTypes[3] {
		return e.Pdir, nil
	}
	return nil, &NotLoadedError{edge: "pdir"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Dir) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dir.FieldID:
			values[i] = new(sql.NullInt64)
		case dir.FieldName:
			values[i] = new(sql.NullString)
		case dir.FieldCreateTime, dir.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		case dir.ForeignKeys[0]: // user_dirs
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Dir fields.
func (d *Dir) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dir.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			d.ID = uint64(value.Int64)
		case dir.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				d.CreateTime = value.Time
			}
		case dir.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				d.UpdateTime = value.Time
			}
		case dir.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				d.Name = value.String
			}
		case dir.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_dirs", value)
			} else if value.Valid {
				d.user_dirs = new(uint64)
				*d.user_dirs = uint64(value.Int64)
			}
		default:
			d.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Dir.
// This includes values selected through modifiers, order, etc.
func (d *Dir) Value(name string) (ent.Value, error) {
	return d.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the Dir entity.
func (d *Dir) QueryOwner() *UserQuery {
	return NewDirClient(d.config).QueryOwner(d)
}

// QuerySaves queries the "saves" edge of the Dir entity.
func (d *Dir) QuerySaves() *SavedQuery {
	return NewDirClient(d.config).QuerySaves(d)
}

// QuerySubdir queries the "subdir" edge of the Dir entity.
func (d *Dir) QuerySubdir() *DirQuery {
	return NewDirClient(d.config).QuerySubdir(d)
}

// QueryPdir queries the "pdir" edge of the Dir entity.
func (d *Dir) QueryPdir() *DirQuery {
	return NewDirClient(d.config).QueryPdir(d)
}

// Update returns a builder for updating this Dir.
// Note that you need to call Dir.Unwrap() before calling this method if this Dir
// was returned from a transaction, and the transaction was committed or rolled back.
func (d *Dir) Update() *DirUpdateOne {
	return NewDirClient(d.config).UpdateOne(d)
}

// Unwrap unwraps the Dir entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (d *Dir) Unwrap() *Dir {
	_tx, ok := d.config.driver.(*txDriver)
	if !ok {
		panic("ent: Dir is not a transactional entity")
	}
	d.config.driver = _tx.drv
	return d
}

// String implements the fmt.Stringer.
func (d *Dir) String() string {
	var builder strings.Builder
	builder.WriteString("Dir(")
	builder.WriteString(fmt.Sprintf("id=%v, ", d.ID))
	builder.WriteString("create_time=")
	builder.WriteString(d.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(d.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(d.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Dirs is a parsable slice of Dir.
type Dirs []*Dir
