// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/disism/saikan/ent/albums"
	"github.com/disism/saikan/ent/files"
	"github.com/disism/saikan/ent/images"
	"github.com/disism/saikan/ent/playlists"
	"github.com/disism/saikan/ent/predicate"
)

// ImagesQuery is the builder for querying Images entities.
type ImagesQuery struct {
	config
	ctx           *QueryContext
	order         []images.OrderOption
	inters        []Interceptor
	predicates    []predicate.Images
	withFile      *FilesQuery
	withAlbums    *AlbumsQuery
	withPlaylists *PlaylistsQuery
	withFKs       bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ImagesQuery builder.
func (iq *ImagesQuery) Where(ps ...predicate.Images) *ImagesQuery {
	iq.predicates = append(iq.predicates, ps...)
	return iq
}

// Limit the number of records to be returned by this query.
func (iq *ImagesQuery) Limit(limit int) *ImagesQuery {
	iq.ctx.Limit = &limit
	return iq
}

// Offset to start from.
func (iq *ImagesQuery) Offset(offset int) *ImagesQuery {
	iq.ctx.Offset = &offset
	return iq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (iq *ImagesQuery) Unique(unique bool) *ImagesQuery {
	iq.ctx.Unique = &unique
	return iq
}

// Order specifies how the records should be ordered.
func (iq *ImagesQuery) Order(o ...images.OrderOption) *ImagesQuery {
	iq.order = append(iq.order, o...)
	return iq
}

// QueryFile chains the current query on the "file" edge.
func (iq *ImagesQuery) QueryFile() *FilesQuery {
	query := (&FilesClient{config: iq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := iq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := iq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(images.Table, images.FieldID, selector),
			sqlgraph.To(files.Table, files.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, images.FileTable, images.FileColumn),
		)
		fromU = sqlgraph.SetNeighbors(iq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAlbums chains the current query on the "albums" edge.
func (iq *ImagesQuery) QueryAlbums() *AlbumsQuery {
	query := (&AlbumsClient{config: iq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := iq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := iq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(images.Table, images.FieldID, selector),
			sqlgraph.To(albums.Table, albums.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, images.AlbumsTable, images.AlbumsColumn),
		)
		fromU = sqlgraph.SetNeighbors(iq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPlaylists chains the current query on the "playlists" edge.
func (iq *ImagesQuery) QueryPlaylists() *PlaylistsQuery {
	query := (&PlaylistsClient{config: iq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := iq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := iq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(images.Table, images.FieldID, selector),
			sqlgraph.To(playlists.Table, playlists.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, images.PlaylistsTable, images.PlaylistsColumn),
		)
		fromU = sqlgraph.SetNeighbors(iq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Images entity from the query.
// Returns a *NotFoundError when no Images was found.
func (iq *ImagesQuery) First(ctx context.Context) (*Images, error) {
	nodes, err := iq.Limit(1).All(setContextOp(ctx, iq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{images.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (iq *ImagesQuery) FirstX(ctx context.Context) *Images {
	node, err := iq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Images ID from the query.
// Returns a *NotFoundError when no Images ID was found.
func (iq *ImagesQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = iq.Limit(1).IDs(setContextOp(ctx, iq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{images.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (iq *ImagesQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := iq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Images entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Images entity is found.
// Returns a *NotFoundError when no Images entities are found.
func (iq *ImagesQuery) Only(ctx context.Context) (*Images, error) {
	nodes, err := iq.Limit(2).All(setContextOp(ctx, iq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{images.Label}
	default:
		return nil, &NotSingularError{images.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (iq *ImagesQuery) OnlyX(ctx context.Context) *Images {
	node, err := iq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Images ID in the query.
// Returns a *NotSingularError when more than one Images ID is found.
// Returns a *NotFoundError when no entities are found.
func (iq *ImagesQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = iq.Limit(2).IDs(setContextOp(ctx, iq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{images.Label}
	default:
		err = &NotSingularError{images.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (iq *ImagesQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := iq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ImagesSlice.
func (iq *ImagesQuery) All(ctx context.Context) ([]*Images, error) {
	ctx = setContextOp(ctx, iq.ctx, "All")
	if err := iq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Images, *ImagesQuery]()
	return withInterceptors[[]*Images](ctx, iq, qr, iq.inters)
}

// AllX is like All, but panics if an error occurs.
func (iq *ImagesQuery) AllX(ctx context.Context) []*Images {
	nodes, err := iq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Images IDs.
func (iq *ImagesQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if iq.ctx.Unique == nil && iq.path != nil {
		iq.Unique(true)
	}
	ctx = setContextOp(ctx, iq.ctx, "IDs")
	if err = iq.Select(images.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (iq *ImagesQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := iq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (iq *ImagesQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, iq.ctx, "Count")
	if err := iq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, iq, querierCount[*ImagesQuery](), iq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (iq *ImagesQuery) CountX(ctx context.Context) int {
	count, err := iq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (iq *ImagesQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, iq.ctx, "Exist")
	switch _, err := iq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (iq *ImagesQuery) ExistX(ctx context.Context) bool {
	exist, err := iq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ImagesQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (iq *ImagesQuery) Clone() *ImagesQuery {
	if iq == nil {
		return nil
	}
	return &ImagesQuery{
		config:        iq.config,
		ctx:           iq.ctx.Clone(),
		order:         append([]images.OrderOption{}, iq.order...),
		inters:        append([]Interceptor{}, iq.inters...),
		predicates:    append([]predicate.Images{}, iq.predicates...),
		withFile:      iq.withFile.Clone(),
		withAlbums:    iq.withAlbums.Clone(),
		withPlaylists: iq.withPlaylists.Clone(),
		// clone intermediate query.
		sql:  iq.sql.Clone(),
		path: iq.path,
	}
}

// WithFile tells the query-builder to eager-load the nodes that are connected to
// the "file" edge. The optional arguments are used to configure the query builder of the edge.
func (iq *ImagesQuery) WithFile(opts ...func(*FilesQuery)) *ImagesQuery {
	query := (&FilesClient{config: iq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	iq.withFile = query
	return iq
}

// WithAlbums tells the query-builder to eager-load the nodes that are connected to
// the "albums" edge. The optional arguments are used to configure the query builder of the edge.
func (iq *ImagesQuery) WithAlbums(opts ...func(*AlbumsQuery)) *ImagesQuery {
	query := (&AlbumsClient{config: iq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	iq.withAlbums = query
	return iq
}

// WithPlaylists tells the query-builder to eager-load the nodes that are connected to
// the "playlists" edge. The optional arguments are used to configure the query builder of the edge.
func (iq *ImagesQuery) WithPlaylists(opts ...func(*PlaylistsQuery)) *ImagesQuery {
	query := (&PlaylistsClient{config: iq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	iq.withPlaylists = query
	return iq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Images.Query().
//		GroupBy(images.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (iq *ImagesQuery) GroupBy(field string, fields ...string) *ImagesGroupBy {
	iq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ImagesGroupBy{build: iq}
	grbuild.flds = &iq.ctx.Fields
	grbuild.label = images.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.Images.Query().
//		Select(images.FieldCreateTime).
//		Scan(ctx, &v)
func (iq *ImagesQuery) Select(fields ...string) *ImagesSelect {
	iq.ctx.Fields = append(iq.ctx.Fields, fields...)
	sbuild := &ImagesSelect{ImagesQuery: iq}
	sbuild.label = images.Label
	sbuild.flds, sbuild.scan = &iq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ImagesSelect configured with the given aggregations.
func (iq *ImagesQuery) Aggregate(fns ...AggregateFunc) *ImagesSelect {
	return iq.Select().Aggregate(fns...)
}

func (iq *ImagesQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range iq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, iq); err != nil {
				return err
			}
		}
	}
	for _, f := range iq.ctx.Fields {
		if !images.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if iq.path != nil {
		prev, err := iq.path(ctx)
		if err != nil {
			return err
		}
		iq.sql = prev
	}
	return nil
}

func (iq *ImagesQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Images, error) {
	var (
		nodes       = []*Images{}
		withFKs     = iq.withFKs
		_spec       = iq.querySpec()
		loadedTypes = [3]bool{
			iq.withFile != nil,
			iq.withAlbums != nil,
			iq.withPlaylists != nil,
		}
	)
	if iq.withFile != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, images.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Images).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Images{config: iq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, iq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := iq.withFile; query != nil {
		if err := iq.loadFile(ctx, query, nodes, nil,
			func(n *Images, e *Files) { n.Edges.File = e }); err != nil {
			return nil, err
		}
	}
	if query := iq.withAlbums; query != nil {
		if err := iq.loadAlbums(ctx, query, nodes,
			func(n *Images) { n.Edges.Albums = []*Albums{} },
			func(n *Images, e *Albums) { n.Edges.Albums = append(n.Edges.Albums, e) }); err != nil {
			return nil, err
		}
	}
	if query := iq.withPlaylists; query != nil {
		if err := iq.loadPlaylists(ctx, query, nodes,
			func(n *Images) { n.Edges.Playlists = []*Playlists{} },
			func(n *Images, e *Playlists) { n.Edges.Playlists = append(n.Edges.Playlists, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (iq *ImagesQuery) loadFile(ctx context.Context, query *FilesQuery, nodes []*Images, init func(*Images), assign func(*Images, *Files)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*Images)
	for i := range nodes {
		if nodes[i].files_images == nil {
			continue
		}
		fk := *nodes[i].files_images
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(files.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "files_images" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (iq *ImagesQuery) loadAlbums(ctx context.Context, query *AlbumsQuery, nodes []*Images, init func(*Images), assign func(*Images, *Albums)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uint64]*Images)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Albums(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(images.AlbumsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.images_albums
		if fk == nil {
			return fmt.Errorf(`foreign-key "images_albums" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "images_albums" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (iq *ImagesQuery) loadPlaylists(ctx context.Context, query *PlaylistsQuery, nodes []*Images, init func(*Images), assign func(*Images, *Playlists)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uint64]*Images)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Playlists(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(images.PlaylistsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.images_playlists
		if fk == nil {
			return fmt.Errorf(`foreign-key "images_playlists" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "images_playlists" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (iq *ImagesQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := iq.querySpec()
	_spec.Node.Columns = iq.ctx.Fields
	if len(iq.ctx.Fields) > 0 {
		_spec.Unique = iq.ctx.Unique != nil && *iq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, iq.driver, _spec)
}

func (iq *ImagesQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(images.Table, images.Columns, sqlgraph.NewFieldSpec(images.FieldID, field.TypeUint64))
	_spec.From = iq.sql
	if unique := iq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if iq.path != nil {
		_spec.Unique = true
	}
	if fields := iq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, images.FieldID)
		for i := range fields {
			if fields[i] != images.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := iq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := iq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := iq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := iq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (iq *ImagesQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(iq.driver.Dialect())
	t1 := builder.Table(images.Table)
	columns := iq.ctx.Fields
	if len(columns) == 0 {
		columns = images.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if iq.sql != nil {
		selector = iq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if iq.ctx.Unique != nil && *iq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range iq.predicates {
		p(selector)
	}
	for _, p := range iq.order {
		p(selector)
	}
	if offset := iq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := iq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ImagesGroupBy is the group-by builder for Images entities.
type ImagesGroupBy struct {
	selector
	build *ImagesQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (igb *ImagesGroupBy) Aggregate(fns ...AggregateFunc) *ImagesGroupBy {
	igb.fns = append(igb.fns, fns...)
	return igb
}

// Scan applies the selector query and scans the result into the given value.
func (igb *ImagesGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, igb.build.ctx, "GroupBy")
	if err := igb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ImagesQuery, *ImagesGroupBy](ctx, igb.build, igb, igb.build.inters, v)
}

func (igb *ImagesGroupBy) sqlScan(ctx context.Context, root *ImagesQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(igb.fns))
	for _, fn := range igb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*igb.flds)+len(igb.fns))
		for _, f := range *igb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*igb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := igb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ImagesSelect is the builder for selecting fields of Images entities.
type ImagesSelect struct {
	*ImagesQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (is *ImagesSelect) Aggregate(fns ...AggregateFunc) *ImagesSelect {
	is.fns = append(is.fns, fns...)
	return is
}

// Scan applies the selector query and scans the result into the given value.
func (is *ImagesSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, is.ctx, "Select")
	if err := is.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ImagesQuery, *ImagesSelect](ctx, is.ImagesQuery, is, is.inters, v)
}

func (is *ImagesSelect) sqlScan(ctx context.Context, root *ImagesQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(is.fns))
	for _, fn := range is.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*is.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := is.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
