// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/disism/saikan/ent/file"
	"github.com/disism/saikan/ent/saved"
	"github.com/disism/saikan/ent/user"
)

// Saved is the model entity for the Saved schema.
type Saved struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// the descriptive text or title of a document, image, or other media element. It is used to provide a short description of the content, characteristics or context of a document.
	Caption string `json:"caption,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SavedQuery when eager-loading is set.
	Edges        SavedEdges `json:"edges"`
	file_saves   *uint64
	user_saves   *uint64
	selectValues sql.SelectValues
}

// SavedEdges holds the relations/edges for other nodes in the graph.
type SavedEdges struct {
	// File holds the value of the file edge.
	File *File `json:"file,omitempty"`
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// Dir holds the value of the dir edge.
	Dir []*Dir `json:"dir,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// FileOrErr returns the File value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SavedEdges) FileOrErr() (*File, error) {
	if e.loadedTypes[0] {
		if e.File == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: file.Label}
		}
		return e.File, nil
	}
	return nil, &NotLoadedError{edge: "file"}
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SavedEdges) OwnerOrErr() (*User, error) {
	if e.loadedTypes[1] {
		if e.Owner == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.Owner, nil
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// DirOrErr returns the Dir value or an error if the edge
// was not loaded in eager-loading.
func (e SavedEdges) DirOrErr() ([]*Dir, error) {
	if e.loadedTypes[2] {
		return e.Dir, nil
	}
	return nil, &NotLoadedError{edge: "dir"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Saved) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case saved.FieldID:
			values[i] = new(sql.NullInt64)
		case saved.FieldName, saved.FieldCaption:
			values[i] = new(sql.NullString)
		case saved.FieldCreateTime, saved.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		case saved.ForeignKeys[0]: // file_saves
			values[i] = new(sql.NullInt64)
		case saved.ForeignKeys[1]: // user_saves
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Saved fields.
func (s *Saved) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case saved.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			s.ID = uint64(value.Int64)
		case saved.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				s.CreateTime = value.Time
			}
		case saved.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				s.UpdateTime = value.Time
			}
		case saved.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				s.Name = value.String
			}
		case saved.FieldCaption:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field caption", values[i])
			} else if value.Valid {
				s.Caption = value.String
			}
		case saved.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field file_saves", value)
			} else if value.Valid {
				s.file_saves = new(uint64)
				*s.file_saves = uint64(value.Int64)
			}
		case saved.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_saves", value)
			} else if value.Valid {
				s.user_saves = new(uint64)
				*s.user_saves = uint64(value.Int64)
			}
		default:
			s.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Saved.
// This includes values selected through modifiers, order, etc.
func (s *Saved) Value(name string) (ent.Value, error) {
	return s.selectValues.Get(name)
}

// QueryFile queries the "file" edge of the Saved entity.
func (s *Saved) QueryFile() *FileQuery {
	return NewSavedClient(s.config).QueryFile(s)
}

// QueryOwner queries the "owner" edge of the Saved entity.
func (s *Saved) QueryOwner() *UserQuery {
	return NewSavedClient(s.config).QueryOwner(s)
}

// QueryDir queries the "dir" edge of the Saved entity.
func (s *Saved) QueryDir() *DirQuery {
	return NewSavedClient(s.config).QueryDir(s)
}

// Update returns a builder for updating this Saved.
// Note that you need to call Saved.Unwrap() before calling this method if this Saved
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Saved) Update() *SavedUpdateOne {
	return NewSavedClient(s.config).UpdateOne(s)
}

// Unwrap unwraps the Saved entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Saved) Unwrap() *Saved {
	_tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Saved is not a transactional entity")
	}
	s.config.driver = _tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Saved) String() string {
	var builder strings.Builder
	builder.WriteString("Saved(")
	builder.WriteString(fmt.Sprintf("id=%v, ", s.ID))
	builder.WriteString("create_time=")
	builder.WriteString(s.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(s.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(s.Name)
	builder.WriteString(", ")
	builder.WriteString("caption=")
	builder.WriteString(s.Caption)
	builder.WriteByte(')')
	return builder.String()
}

// Saveds is a parsable slice of Saved.
type Saveds []*Saved
