// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/disism/saikan/ent/dir"
	"github.com/disism/saikan/ent/file"
	"github.com/disism/saikan/ent/predicate"
	"github.com/disism/saikan/ent/saved"
	"github.com/disism/saikan/ent/user"
)

// SavedUpdate is the builder for updating Saved entities.
type SavedUpdate struct {
	config
	hooks    []Hook
	mutation *SavedMutation
}

// Where appends a list predicates to the SavedUpdate builder.
func (su *SavedUpdate) Where(ps ...predicate.Saved) *SavedUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetUpdateTime sets the "update_time" field.
func (su *SavedUpdate) SetUpdateTime(t time.Time) *SavedUpdate {
	su.mutation.SetUpdateTime(t)
	return su
}

// SetName sets the "name" field.
func (su *SavedUpdate) SetName(s string) *SavedUpdate {
	su.mutation.SetName(s)
	return su
}

// SetNillableName sets the "name" field if the given value is not nil.
func (su *SavedUpdate) SetNillableName(s *string) *SavedUpdate {
	if s != nil {
		su.SetName(*s)
	}
	return su
}

// SetCaption sets the "caption" field.
func (su *SavedUpdate) SetCaption(s string) *SavedUpdate {
	su.mutation.SetCaption(s)
	return su
}

// SetNillableCaption sets the "caption" field if the given value is not nil.
func (su *SavedUpdate) SetNillableCaption(s *string) *SavedUpdate {
	if s != nil {
		su.SetCaption(*s)
	}
	return su
}

// ClearCaption clears the value of the "caption" field.
func (su *SavedUpdate) ClearCaption() *SavedUpdate {
	su.mutation.ClearCaption()
	return su
}

// SetFileID sets the "file" edge to the File entity by ID.
func (su *SavedUpdate) SetFileID(id uint64) *SavedUpdate {
	su.mutation.SetFileID(id)
	return su
}

// SetNillableFileID sets the "file" edge to the File entity by ID if the given value is not nil.
func (su *SavedUpdate) SetNillableFileID(id *uint64) *SavedUpdate {
	if id != nil {
		su = su.SetFileID(*id)
	}
	return su
}

// SetFile sets the "file" edge to the File entity.
func (su *SavedUpdate) SetFile(f *File) *SavedUpdate {
	return su.SetFileID(f.ID)
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (su *SavedUpdate) SetOwnerID(id uint64) *SavedUpdate {
	su.mutation.SetOwnerID(id)
	return su
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (su *SavedUpdate) SetNillableOwnerID(id *uint64) *SavedUpdate {
	if id != nil {
		su = su.SetOwnerID(*id)
	}
	return su
}

// SetOwner sets the "owner" edge to the User entity.
func (su *SavedUpdate) SetOwner(u *User) *SavedUpdate {
	return su.SetOwnerID(u.ID)
}

// AddDirIDs adds the "dir" edge to the Dir entity by IDs.
func (su *SavedUpdate) AddDirIDs(ids ...uint64) *SavedUpdate {
	su.mutation.AddDirIDs(ids...)
	return su
}

// AddDir adds the "dir" edges to the Dir entity.
func (su *SavedUpdate) AddDir(d ...*Dir) *SavedUpdate {
	ids := make([]uint64, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return su.AddDirIDs(ids...)
}

// Mutation returns the SavedMutation object of the builder.
func (su *SavedUpdate) Mutation() *SavedMutation {
	return su.mutation
}

// ClearFile clears the "file" edge to the File entity.
func (su *SavedUpdate) ClearFile() *SavedUpdate {
	su.mutation.ClearFile()
	return su
}

// ClearOwner clears the "owner" edge to the User entity.
func (su *SavedUpdate) ClearOwner() *SavedUpdate {
	su.mutation.ClearOwner()
	return su
}

// ClearDir clears all "dir" edges to the Dir entity.
func (su *SavedUpdate) ClearDir() *SavedUpdate {
	su.mutation.ClearDir()
	return su
}

// RemoveDirIDs removes the "dir" edge to Dir entities by IDs.
func (su *SavedUpdate) RemoveDirIDs(ids ...uint64) *SavedUpdate {
	su.mutation.RemoveDirIDs(ids...)
	return su
}

// RemoveDir removes "dir" edges to Dir entities.
func (su *SavedUpdate) RemoveDir(d ...*Dir) *SavedUpdate {
	ids := make([]uint64, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return su.RemoveDirIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SavedUpdate) Save(ctx context.Context) (int, error) {
	su.defaults()
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SavedUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SavedUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SavedUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (su *SavedUpdate) defaults() {
	if _, ok := su.mutation.UpdateTime(); !ok {
		v := saved.UpdateDefaultUpdateTime()
		su.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *SavedUpdate) check() error {
	if v, ok := su.mutation.Name(); ok {
		if err := saved.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Saved.name": %w`, err)}
		}
	}
	if v, ok := su.mutation.Caption(); ok {
		if err := saved.CaptionValidator(v); err != nil {
			return &ValidationError{Name: "caption", err: fmt.Errorf(`ent: validator failed for field "Saved.caption": %w`, err)}
		}
	}
	return nil
}

func (su *SavedUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := su.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(saved.Table, saved.Columns, sqlgraph.NewFieldSpec(saved.FieldID, field.TypeUint64))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.UpdateTime(); ok {
		_spec.SetField(saved.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := su.mutation.Name(); ok {
		_spec.SetField(saved.FieldName, field.TypeString, value)
	}
	if value, ok := su.mutation.Caption(); ok {
		_spec.SetField(saved.FieldCaption, field.TypeString, value)
	}
	if su.mutation.CaptionCleared() {
		_spec.ClearField(saved.FieldCaption, field.TypeString)
	}
	if su.mutation.FileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   saved.FileTable,
			Columns: []string{saved.FileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.FileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   saved.FileTable,
			Columns: []string{saved.FileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   saved.OwnerTable,
			Columns: []string{saved.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   saved.OwnerTable,
			Columns: []string{saved.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.DirCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   saved.DirTable,
			Columns: saved.DirPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dir.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedDirIDs(); len(nodes) > 0 && !su.mutation.DirCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   saved.DirTable,
			Columns: saved.DirPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dir.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.DirIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   saved.DirTable,
			Columns: saved.DirPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dir.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{saved.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SavedUpdateOne is the builder for updating a single Saved entity.
type SavedUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SavedMutation
}

// SetUpdateTime sets the "update_time" field.
func (suo *SavedUpdateOne) SetUpdateTime(t time.Time) *SavedUpdateOne {
	suo.mutation.SetUpdateTime(t)
	return suo
}

// SetName sets the "name" field.
func (suo *SavedUpdateOne) SetName(s string) *SavedUpdateOne {
	suo.mutation.SetName(s)
	return suo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (suo *SavedUpdateOne) SetNillableName(s *string) *SavedUpdateOne {
	if s != nil {
		suo.SetName(*s)
	}
	return suo
}

// SetCaption sets the "caption" field.
func (suo *SavedUpdateOne) SetCaption(s string) *SavedUpdateOne {
	suo.mutation.SetCaption(s)
	return suo
}

// SetNillableCaption sets the "caption" field if the given value is not nil.
func (suo *SavedUpdateOne) SetNillableCaption(s *string) *SavedUpdateOne {
	if s != nil {
		suo.SetCaption(*s)
	}
	return suo
}

// ClearCaption clears the value of the "caption" field.
func (suo *SavedUpdateOne) ClearCaption() *SavedUpdateOne {
	suo.mutation.ClearCaption()
	return suo
}

// SetFileID sets the "file" edge to the File entity by ID.
func (suo *SavedUpdateOne) SetFileID(id uint64) *SavedUpdateOne {
	suo.mutation.SetFileID(id)
	return suo
}

// SetNillableFileID sets the "file" edge to the File entity by ID if the given value is not nil.
func (suo *SavedUpdateOne) SetNillableFileID(id *uint64) *SavedUpdateOne {
	if id != nil {
		suo = suo.SetFileID(*id)
	}
	return suo
}

// SetFile sets the "file" edge to the File entity.
func (suo *SavedUpdateOne) SetFile(f *File) *SavedUpdateOne {
	return suo.SetFileID(f.ID)
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (suo *SavedUpdateOne) SetOwnerID(id uint64) *SavedUpdateOne {
	suo.mutation.SetOwnerID(id)
	return suo
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (suo *SavedUpdateOne) SetNillableOwnerID(id *uint64) *SavedUpdateOne {
	if id != nil {
		suo = suo.SetOwnerID(*id)
	}
	return suo
}

// SetOwner sets the "owner" edge to the User entity.
func (suo *SavedUpdateOne) SetOwner(u *User) *SavedUpdateOne {
	return suo.SetOwnerID(u.ID)
}

// AddDirIDs adds the "dir" edge to the Dir entity by IDs.
func (suo *SavedUpdateOne) AddDirIDs(ids ...uint64) *SavedUpdateOne {
	suo.mutation.AddDirIDs(ids...)
	return suo
}

// AddDir adds the "dir" edges to the Dir entity.
func (suo *SavedUpdateOne) AddDir(d ...*Dir) *SavedUpdateOne {
	ids := make([]uint64, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return suo.AddDirIDs(ids...)
}

// Mutation returns the SavedMutation object of the builder.
func (suo *SavedUpdateOne) Mutation() *SavedMutation {
	return suo.mutation
}

// ClearFile clears the "file" edge to the File entity.
func (suo *SavedUpdateOne) ClearFile() *SavedUpdateOne {
	suo.mutation.ClearFile()
	return suo
}

// ClearOwner clears the "owner" edge to the User entity.
func (suo *SavedUpdateOne) ClearOwner() *SavedUpdateOne {
	suo.mutation.ClearOwner()
	return suo
}

// ClearDir clears all "dir" edges to the Dir entity.
func (suo *SavedUpdateOne) ClearDir() *SavedUpdateOne {
	suo.mutation.ClearDir()
	return suo
}

// RemoveDirIDs removes the "dir" edge to Dir entities by IDs.
func (suo *SavedUpdateOne) RemoveDirIDs(ids ...uint64) *SavedUpdateOne {
	suo.mutation.RemoveDirIDs(ids...)
	return suo
}

// RemoveDir removes "dir" edges to Dir entities.
func (suo *SavedUpdateOne) RemoveDir(d ...*Dir) *SavedUpdateOne {
	ids := make([]uint64, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return suo.RemoveDirIDs(ids...)
}

// Where appends a list predicates to the SavedUpdate builder.
func (suo *SavedUpdateOne) Where(ps ...predicate.Saved) *SavedUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SavedUpdateOne) Select(field string, fields ...string) *SavedUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Saved entity.
func (suo *SavedUpdateOne) Save(ctx context.Context) (*Saved, error) {
	suo.defaults()
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SavedUpdateOne) SaveX(ctx context.Context) *Saved {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SavedUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SavedUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (suo *SavedUpdateOne) defaults() {
	if _, ok := suo.mutation.UpdateTime(); !ok {
		v := saved.UpdateDefaultUpdateTime()
		suo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *SavedUpdateOne) check() error {
	if v, ok := suo.mutation.Name(); ok {
		if err := saved.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Saved.name": %w`, err)}
		}
	}
	if v, ok := suo.mutation.Caption(); ok {
		if err := saved.CaptionValidator(v); err != nil {
			return &ValidationError{Name: "caption", err: fmt.Errorf(`ent: validator failed for field "Saved.caption": %w`, err)}
		}
	}
	return nil
}

func (suo *SavedUpdateOne) sqlSave(ctx context.Context) (_node *Saved, err error) {
	if err := suo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(saved.Table, saved.Columns, sqlgraph.NewFieldSpec(saved.FieldID, field.TypeUint64))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Saved.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, saved.FieldID)
		for _, f := range fields {
			if !saved.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != saved.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.UpdateTime(); ok {
		_spec.SetField(saved.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := suo.mutation.Name(); ok {
		_spec.SetField(saved.FieldName, field.TypeString, value)
	}
	if value, ok := suo.mutation.Caption(); ok {
		_spec.SetField(saved.FieldCaption, field.TypeString, value)
	}
	if suo.mutation.CaptionCleared() {
		_spec.ClearField(saved.FieldCaption, field.TypeString)
	}
	if suo.mutation.FileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   saved.FileTable,
			Columns: []string{saved.FileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.FileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   saved.FileTable,
			Columns: []string{saved.FileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   saved.OwnerTable,
			Columns: []string{saved.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   saved.OwnerTable,
			Columns: []string{saved.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.DirCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   saved.DirTable,
			Columns: saved.DirPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dir.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedDirIDs(); len(nodes) > 0 && !suo.mutation.DirCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   saved.DirTable,
			Columns: saved.DirPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dir.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.DirIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   saved.DirTable,
			Columns: saved.DirPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dir.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Saved{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{saved.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
